### PR TITLE
Household relationships

### PR DESCRIPTION
**Pull request by celloward**
Adding spouse and child joins, validations, and tests to the Person model.

### CODE REVIEW

**Comment by rudyrigot** [comment]
Hi Jeremy,

I'm glad we were matched by DevTogether to figure this one out!

I have to admit I'm a bit confused about the model, so I may need your explanations. On the self-references from person to person, as spouses and parent-child, I believe I get it and I believe that's the one you have questions about; but I am a bit lost about leadership/ministry and how you mean them to relate to a person, can you explain it to me real quick? Let me know if they're out of scope for now and it's too early to look into, that would also be fine (I have noticed that there are no tests for it yet).

I'm thinking of a potential issue with the way things are modeled about spouses: if one assigns A as a spouse to B, I believe it doesn't make B be a spouse to A, am I correct?

I've looked into your test failures realy quick, and I believe your `ChildValidator` one seems to pass when renaming `ChildValidator#validator` to `ChildValidator#validate`, which I believe is what ActiveRecord expects.

The living spouse test failure seems to be hairier (and therefore possibly more fun to look into!), I propose we investigate it together on Tuesday evening!

As a side note, if you intend for this to be a real project, I have an intuition that you would have to write a fair amount of business logic around genealogy which doesn't sound like it would be much different from other projects doing genealogy stuff. It may be worthwhile to look into ActiveRecord gems for that use case, which I'm sure come with a lot of primitives you could get to reuse for free (siblings, grand-parents, ...). We could also look into them together on Tuesday too!

**Comment by celloward** [comment]
Hi Rudy,
I'm glad we got matched as well, and look forward to working with you on
this. I'm developing the app for my church to have a centralized database
with contact and relevant biographical information for our members. This
information will be fully accessible to admin (church leadership) and to a
more limited extent,  to the other members through an online,
password-protected directory of member contact info.

I should explain that "members" is an official designation of our church
for people who have gone through a formal process and have more ownership
of the church functions. I originally called the main model in question the
Member model, but there were some nuances that required me to change it to
Person with a column in the table that has a Boolean for Member.

You were totally right about the ChildValidator method. Thanks for pointing
that out.

Here are the complexities I am trying to model in the data for spouses
specifically:

   1. Marriages should be reciprocal (i.e. if A is a spouse to B, B should
   be a spouse to A automatically).
   2. Members can have numerous previous marriages (through death or
   divorce) but obviously not polygamous ones (hence the test that is
   currently failing).
   3. Once married, even if they become separated by death or divorce,
   there should be a permanent record of their relationship. (A new marriage
   should not erase the existence of a previous one.)

It's a good suggestion to look into genealogy gems, but we won't need to
keep track of more than the parent/child and spousal relationships. The
biographical information should scope within the current church membership
for practical use. I don't intend to trace a family tree past one link. Of
course if there's a ready gem solution to the spousal problem in question,
we should definitely look at that.

You mentioned ministry/leadership. I have done some work on it but haven't
quite finished, and would love to work on this too if we have time. Here
are my thoughts currently on that:

   1. Members can be leaders of ministries (aka teams or programs in the
   church) and ministries can have multiple leaders. I was intending to show
   that connection through the "has_many, through: :leadership" association.
   2. Members can also be participants in ministries under the leadership
   of the ministry leader. I haven't yet figured out how I want to show this
   association.
   3. Endgame: We want to be able to see which members are leading a
   particular ministry, which ministries a member leads, and which members are
   participants in a particular ministry.

If we really blast through all that, maybe we can start looking at creating
a User model with username and password that would connect up to an already
existing Person in the database. I want to be able to email people the link
to their User creation page linked to their database listing.

Let me know if you have any other questions or thoughts. I'll be working
pretty heavily on this Monday and Tuesday. I look forward to meeting you in
a few days!

Jeremy

**Comment by rudyrigot** [comment]
Ah, now that I understand better your use case, I fully second your decision to just set membership status as a boolean on a Person model. 👍

It sounds like there should be a many-to-many relationship between ministries and their leaders, and between ministries and their members, if I understood correctly, so you would need some join tables if I got it right. I think I'm going to need us to draw this with a good ol' pen and paper to be sure. Let's talk it through on Tuesday.

For the spousal relationship, you really seem close with what you have right now. Besides your failing validator, the only bit you seem to miss is some callback to ensure the relationship is written on both records. Or, you may want to only write it on one of them and always query the other. Let's talk about it!

Another option there is would be to have a many-to-many `past_spouses` field, and a one-to-one `current_spouse` field. When married people would either divorce or pass away, you would move them from the former to the latter. I'm not strongly opinionated at all about this way or the way you did it, I'm just thinking of it as another way to do it.

Anyway, let's talk about it more tomorrow!

**Comment by rudyrigot** [comment]
Oh, one more thought: totally got it that your genealogy need is basic and may not require to reuse something else. About authentication though, it's a lot of business logic that is similar across needs, and that is also very security-sensitive, so if I were you, I would certainly favor re-using something on this one.

The one I've always used with Rails, whether for my own small side-projects with 3 users, or for the $20M-in-ARR startup I was working for until recently, is this one: https://github.com/plataformatec/devise

If you're interested, we could look into integrating it for your website, I've done it a number of times in the past (even though it's been a while I haven't done it from scratch, but I'm sure we can figure it out).

**Comment by celloward** [comment]
All this is excellent. I am very much looking forward to our meeting, as it
looks like lots to talk about.

I really like the idea of using devise. We should definitely look at that.

Jeremy

**Comment by rudyrigot** [comment]
Sounds perfect!

Note: I’ll probably be somewhat late, because I need to drive from the suburbs after my last meeting ends at 5.30pm, so don’t be surprised if you don’t see me at first.

See you tonight, looking forward to it!

**Comment by celloward** [comment]
Ok. See you later.

**Comment by rudyrigot** [comment]
Hey I’m the building, 14th floor, I have a feeling I’m being sent to the wrong places. Do you know what floor the event is on?

**Pull request closed without merging**
